using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

public class Fixer {
    public static void Fix() {
        string path = @"c:\Users\Diego Schroeder\Desktop\Antigravity\PDE II\script.js";
        string text = File.ReadAllText(path, Encoding.UTF8);
        char a = (char)225; // á

        // Manual fixes for duplicates
        text = text.Replace("text.rep" + a + "g, \" \").rep" + a + "g, \" \");", "text.replace(/[\\n\\r]/g, \" \").replace(/\\s+/g, \" \");");
        text = text.Replace("cleanInput = inp" + a + "g, '');", "cleanInput = input.replace(/[^0-9NSWE.,-]/gi, '');");
        text = text.Replace("emp" + a + "g}", "emp.heading}");
        text = text.Replace("Ax: ${emp" + a + "g}", "Ax: ${emp.heading}");
        text = text.Replace("|| emp" + a + "g;", "|| emp.heading;");
        text = text.Replace("String(emp" + a + "g ||", "String(emp.heading ||");
        text = text.Replace("String(emp" + a + "g).pad", "String(emp.heading).pad");

        // CSS and HTML values
        text = text.Replace("12p" + a + "ground", "12px; background");
        text = text.Replace("6p" + a + "gin", "6px; margin");
        
        // Leaflet & DOM Methods
        text = text.Replace("addP" + a + "ge", "addPage");
        text = text.Replace("ap" + a + "gle", "mapAngle");
        text = text.Replace("ap" + a + "gs", "map.getBounds()");
        text = text.Replace("bindTooltip" + a + "gna" + a + "o", "bindTooltip(`Designação");
        text = text.Replace("blobP" + a + "gth", "blob.length");
        text = text.Replace("bombQtyInp" + a + "ge", "bombQtyInput.addEventListener('change'");
        text = text.Replace("btnHeadingUp" + a + "ght", "btnHeadingUp.style.right");
        text = text.Replace("btnHeadingUp" + a + "ground", "btnHeadingUp.style.background");
        text = text.Replace("canvasP" + a + "gth", "canvas.width");
        text = text.Replace("cap" + a + "getElementById", "captureElement(document.getElementById");
        text = text.Replace("cleanInp" + a + "gth", "cleanInput.length");
        text = text.Replace("comp" + a + "g", "compass-svg");
        text = text.Replace("crop" + a + "g", "crop.toDataURL('image/jpeg'");
        text = text.Replace("crop" + a + "getContext", "crop.getContext");
        text = text.Replace("crop" + a + "ght", "crop.height");
        text = text.Replace("crossP" + a + "gth", "crossProduct(lower[lower.length");
        text = text.Replace("desP" + a + "g", "desPos.lng");
        text = text.Replace("disp" + a + "g", "dispHeading");
        text = text.Replace("dmmP" + a + "gex", "dmmRegex");
        text = text.Replace("dmp" + a + "ge", "dmpi-select').addEventListener('change'");
        text = text.Replace("dmp" + a + "getsCache", "dmpiTargetsCache");
        text = text.Replace("drawEmp" + a + "g", "drawEmployment");
        text = text.Replace("drawingP" + a + "g);", "drawingPoints.push(e.latlng);");
        text = text.Replace("drawingP" + a + "gth", "drawingPoints.length");
        text = text.Replace("drawnTargetMiniP" + a + "gon", "drawnTargetMiniPolygon");
        text = text.Replace("drawnTargetP" + a + "g);", "drawnTargetPoints.push(e.latlng);");
        text = text.Replace("drawnTargetP" + a + "gth", "drawnTargetPoints.length");
        text = text.Replace("Emp" + a + "gada", "Empregada");
        text = text.Replace("emp" + a + "gErr", "emp.longErr");
        text = text.Replace("emp" + a + "getA" + a + "on", "emp.targetAcquisition");
        text = text.Replace("emp" + a + "getCoordsText", "emp.targetCoordsText");
        text = text.Replace("emp" + a + "getElevation", "emp.targetElevation");
        text = text.Replace("emp" + a + "getFolderName", "emp.targetFolderName");
        text = text.Replace("emp" + a + "getMetadata", "emp.targetMetadata");
        text = text.Replace("emp" + a + "gnationCoordsText", "emp.designationCoordsText");
        text = text.Replace("emp" + a + "go", "emprego");
        text = text.Replace("emp" + a + "gonPoints", "emp.targetPolygonPoints");
        text = text.Replace("emp" + a + "gos", "empregos");
        text = text.Replace("emp" + a + "gtId", "emp.targetId");
        text = text.Replace("formatComp" + a + "g", "formatComp(absLng)");
        text = text.Replace("getEmp" + a + "get", "getEmploymentTime(e.target.result");
        text = text.Replace("getMinDistanceToP" + a + "ges", "getMinDistanceToPolygonEdges");
        text = text.Replace("http" + a + "g", "http://www.w3.org/2000/svg");
        text = text.Replace("http" + a + "gle", "https://mt1.google");
        text = text.Replace("hudHeadingInp" + a + "ge", "hudHeadingInput.addEventListener('change'");
        text = text.Replace("imp" + a + "gth", "impacts.length");
        text = text.Replace("inv" + a + "lido", "inválido");
        text = text.Replace("isCircleOverlap" + a + "gon", "isCircleOverlappingPolygon");
        text = text.Replace("isP" + a + "gon", "isPointInPolygon");
        text = text.Replace("jp" + a + "g", "jpeg");
        text = text.Replace("lastMap" + a + "g", "lastMapMouseLatLng");
        text = text.Replace("mainMap" + a + "g", "mainMapImg");
        text = text.Replace("map" + a + "g)", "mapAngle)");
        text = text.Replace("map" + a + "gClientRect", "map.getContainer().getBoundingClientRect");
        text = text.Replace("map" + a + "getA" + a + "ow", "map.removeLayer(drawntargetAcquisitionw)");
        text = text.Replace("map" + a + "getCenter", "map.getCenter");
        text = text.Replace("map" + a + "getContainer", "map.getContainer");
        text = text.Replace("map" + a + "getMarker)", "map.removeLayer(targetMarker)");
        text = text.Replace("map" + a + "getPolyline)", "map.removeLayer(drawnTargetPolyline)");
        text = text.Replace("map" + a + "getZoom", "map.getZoom");
        text = text.Replace("map" + a + "ght", "mapHeight");
        text = text.Replace("map" + a + "gin", "map.getContainer().style.transformOrigin");
        text = text.Replace("map" + a + "gle", "mapAngle");
        text = text.Replace("map" + a + "gnationMarker)", "map.removeLayer(designationMarker)");
        text = text.Replace("map" + a + "gon)", "map.removeLayer(drawnTargetPolygon)");
        text = text.Replace("map" + a + "gt", "map.addLayer(tgt");
        text = text.Replace("miniMap" + a + "g", "miniMap.setView(pos");
        text = text.Replace("miniMap" + a + "gon)", "miniMap.removeLayer(drawnTargetMiniPolygon)");
        text = text.Replace("newP" + a + "g", "newPos.lng");
        text = text.Replace("p" + a + "g)", "p.lng)");
        text = text.Replace("p" + a + "gaƟ", "pregações");
        text = text.Replace("p" + a + "ge =", "pEdge =");
        text = text.Replace("p" + a + "gEl", "pageEl");
        text = text.Replace("p" + a + "geNum", "pageNum");
        text = text.Replace("p" + a + "ges", "pages");
        text = text.Replace("p" + a + "get.value)", "parseCoords(e.target.value)");
        text = text.Replace("p" + a + "getCoordsInput", "parseCoords(targetCoordsInput");
        text = text.Replace("p" + a + "getDocument", "pdfjsLib.getDocument");
        text = text.Replace("p" + a + "getPoints", "L.polyline(drawnTargetPoints");
        text = text.Replace("p" + a + "getTextContent", "page.getTextContent");
        text = text.Replace("p" + a + "ginas", "páginas");
        text = text.Replace("p" + a + "gle", "parseAngle");
        text = text.Replace("p" + a + "gN" + a + "ontent", "parseFloat(node.textContent");
        text = text.Replace("p" + a + "gnationAmeInput", "parseFloat(designationAmeInput");
        text = text.Replace("p" + a + "gnationCoords", "parseCoords(designationCoords");
        text = text.Replace("p" + a + "gon", "polygon");
        text = text.Replace("p" + a + "gono", "polígono");
        text = text.Replace("p" + a + "gonos", "polígonos");
        text = text.Replace("p" + a + "gons", "polygons");
        text = text.Replace("p" + a + "gPoints", "L.polygon(drawnTargetPoints");
        text = text.Replace("p" + a + "gt", "btn-tgt");
        text = text.Replace("p" + a + "gth", "length");
        text = text.Replace("rep" + a + "ght'", "replace('fa-angles-right'");
        text = text.Replace("rep" + a + "gles-left'", "replace('fa-angles-left'");
        text = text.Replace("rulerP" + a + "g);", "rulerPoints.push(e.latlng);");
        text = text.Replace("rulerP" + a + "gs", "rulerPolyline.setLatLngs");
        text = text.Replace("rulerP" + a + "gth", "rulerPoints.length");
        text = text.Replace("savedEmp" + a + "gth", "savedEmployments.length");
        text = text.Replace("setup" + a + "gUp", "setupHeadingUp");
        text = text.Replace("shap" + a + "g()", "shape.getLatLng()");
        text = text.Replace("shap" + a + "gs]", "shape.getLatLngs()]");
        text = text.Replace("simp" + a + "gon", "simplifyPolygon");
        text = text.Replace("simp" + a + "gonPoints", "simplifyPolygonPoints");
        text = text.Replace("simp" + a + "gth", "simplified.length");
        text = text.Replace("sp" + a + "gex", "splitRegex");
        text = text.Replace("stop" + a + "g()", "e.stopPropagation()");
        text = text.Replace("stop" + a + "gation", "stopPropagation");
        text = text.Replace("targetFolderInp" + a + "ge", "targetFolderInput.addEventListener('change'");
        text = text.Replace("targetP" + a + "gth", "targetPolygonPoints.length");
        text = text.Replace("T" + a + "ticos", "Táticos");
        text = text.Replace("telemetryFileInp" + a + "ge", "telemetryFileInput.addEventListener('change'");
        text = text.Replace("toUp" + a + "g", "toUpperCase().replace(/[^A-Z0-9]/g");
        text = text.Replace("up" + a + "g);", "updateDistance();");
        text = text.Replace("up" + a + "getMarker", "updateTargetMarker");
        text = text.Replace("up" + a + "gInfo", "updateHeadingInfo");
        text = text.Replace("up" + a + "gth", "upper.length");
        text = text.Replace("v" + a + "lido", "válido");
        text = text.Replace("v" + a + "lidos", "válidos");
        text = text.Replace("Weap" + a + "g", "Weapon Heading");
        text = text.Replace("weap" + a + "ge", "weaponSelect.addEventListener('change'");
        
        File.WriteAllText(path, text, new UTF8Encoding(false));
    }
}
